import React from "react";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
<<<<<<< HEAD
import { Col } from "react-bootstrap";
=======
import { Col, Row } from "react-bootstrap";
>>>>>>> temp-branch
import "./globals.css";

import styles from "./layout.module.css";
import Header from "./component/Header/header";
import Sidebar from "./component/Sidebar/sidebar";
<<<<<<< HEAD
=======
import 'bootstrap/dist/css/bootstrap.min.css';

>>>>>>> temp-branch
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={styles.container}>
        <div className={styles.header}>
          <Header />
        </div>
<<<<<<< HEAD
        <div className={styles.mainContent}>
=======
        {/* <div className={styles.mainContent}>
>>>>>>> temp-branch
          <Col className={styles.sidebar}>
            <Sidebar />
          </Col>
          <Col className={styles.article}>{children}</Col>
<<<<<<< HEAD
        </div>
=======
        </div> */}
        <Row className={`${styles.mainContent} m-0`}>
          <Col md={0} xl={2} sm={0} xs={0} className={`d-none d-md-none d-xl-block`}>
            <Sidebar />
          </Col>
          <Col className={styles.article} xs={12} sm={12} md={12} xl={10}>{children}</Col>
        </Row>
>>>>>>> temp-branch
      </body>
    </html>
  );
}
