import Header from "./component/Header/header";
import 'bootstrap/dist/css/bootstrap.min.css'; 

export const metadata = {
  title: 'Admin',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
