import React from "react";
import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import { Col } from "react-bootstrap";
import "./globals.css";

import styles from "./layout.module.css";
import Header from "./component/Header/header";
import Sidebar from "./component/Sidebar/sidebar";
export const metadata: Metadata = {
  title: "Admin",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="vi">
      <body className={styles.container}>
        <div className={styles.header}>
          <Header />
        </div>
        <div className={styles.mainContent}>
          <Col className={styles.sidebar}>
            <Sidebar />
          </Col>
          <Col className={styles.article}>{children}</Col>
        </div>
      </body>
    </html>
  );
}
